### ISSUE TITLE
make a CPAN release after #9 is merged

### ISSUE THREAD

**Issue by garu** [mamod/Net-Facebook-Oauth2#10]
Hi @mamod! Me again :)

After #9 is merged (let me know if there is anything I can do to help!), a new version must be pushed to CPAN so we can have upstream code depending on your module force your new released version, otherwise they risk not working anymore after April 30, 2015!

Thanks again for all the great work you've been doing!

Cheers!

**Comment by mamod** [comment]
On my way, I'll add a new release in a couple of days, I'll keep this issue opened until I get the new release on CPAN

**Comment by garu** [comment]
Thanks! Looking forward to it! Let me know if there's anything I can do to help :)

**Comment by mamod** [comment]
New version is on CPAN now, thanks so much, you've already been of a great help :)

**Comment by garu** [comment]
Awesome! @mamod++ \o/
