### ISSUE TITLE
Possibility to choose Facebook API version

### ISSUE THREAD

**Issue by coudot** [mamod/Net-Facebook-Oauth2#15]
The code is using constants to define which API version is used. It could be great to be able to configure this version.

**Comment by mamod** [comment]
@coudot yeah this is a great suggestion, I thought about this yesterday when I was doing a quick review to the new facebook API, I'll see if I can implement this week.

**Comment by garu** [comment]
Hi @coudot! Hi @mamod! If #16 gets merged, we will be able to do this:

```perl
my $fb = Net::Facebook::Oauth2->new(
    api_version => 'v2.11',
    %other_required_params,
);
```

The default is the latest version, `v3.1`.

**Comment by garu** [comment]
Note, however, that we can change the API version being called right now (without the PR merged) by passing `access_token_url` and `authorize_url` with the appropriated version, e.g.

```perl
my $fb = Net::Facebook::Oauth2->new(
    access_token_url => 'https://graph.facebook.com/v2.11/oauth/access_token',
    authorize_url    => 'https://www.facebook.com/v2.11/dialog/oauth',
);
```

But I agree that `api_version` is much simpler to write and easier to maintain! :D
